# Generated by Django 6.0.2 on 2026-03-12 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'API Solutions',
                'verbose_name_plural': 'API Solutions',
                'constraints': [models.UniqueConstraint(fields=('name',), name='api_solution_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('key', models.CharField(max_length=36)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_solutions', models.ManyToManyField(blank=True, null=True, related_name='+', to='app.apisolution')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'indexes': [models.Index(fields=['key'], name='api_key_key_index')],
                'constraints': [models.UniqueConstraint(fields=('key',), name='api_key_key_unique'), models.UniqueConstraint(fields=('name',), name='api_key_name_unique')],
            },
        ),
    ]
