# Generated by Django 6.0.2 on 2026-03-12

from __future__ import annotations

import hashlib
from base64 import urlsafe_b64encode

from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _normalize_scope_slug(value: str) -> str:
    normalized = value.strip().lower().replace("-", "_").replace(" ", "_")
    if "." not in normalized:
        return f"{normalized}.read"
    return normalized


def _get_cipher() -> Fernet:
    key_material = settings.SECRET_KEY.encode("utf-8")
    derived_key = HKDF(
        algorithm=hashes.SHA256(),
        length=32,
        salt=b"app.api_auth.models.APIKey",
        info=b"api-key-encryption",
    ).derive(key_material)
    return Fernet(urlsafe_b64encode(derived_key))


def populate_solution_slugs(apps, _schema_editor) -> None:  # noqa: ANN001
    api_solution_model = apps.get_model("app", "APISolution")
    for solution in api_solution_model.objects.all():
        solution.slug = _normalize_scope_slug(solution.name)
        solution.save(update_fields=["slug"])


def backfill_and_encrypt_api_keys(apps, _schema_editor) -> None:  # noqa: ANN001
    api_key_model = apps.get_model("app", "APIKey")
    cipher = _get_cipher()
    for api_key in api_key_model.objects.all():
        raw_key = api_key.key
        if not raw_key:
            continue

        if not raw_key.startswith("sk_"):
            raw_key = cipher.decrypt(raw_key.encode("utf-8")).decode("utf-8")

        api_key.key_prefix = raw_key[:12]
        api_key.key_hash = hashlib.sha256(raw_key.encode("utf-8")).hexdigest()
        api_key.key = cipher.encrypt(raw_key.encode("utf-8")).decode("utf-8")
        api_key.save(update_fields=["key_prefix", "key_hash", "key"])


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_apisolution_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="apisolution",
            name="slug",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.RunPython(
            code=populate_solution_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="apisolution",
            name="api_solution_name_unique",
        ),
        migrations.RemoveField(
            model_name="apisolution",
            name="name",
        ),
        migrations.AlterField(
            model_name="apisolution",
            name="slug",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="apisolution",
            constraint=models.UniqueConstraint(
                fields=("slug",),
                name="api_solution_slug_unique",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apikey",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(default="", editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="apikey",
            name="key_prefix",
            field=models.CharField(default="", editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name="apikey",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="last_used_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="allowed_solutions",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="app.apisolution",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.TextField(default="", editable=False),
        ),
        migrations.RunPython(
            code=backfill_and_encrypt_api_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="apikey",
            name="api_key_key_unique",
        ),
        migrations.RemoveIndex(
            model_name="apikey",
            name="api_key_key_index",
        ),
        migrations.AddConstraint(
            model_name="apikey",
            constraint=models.UniqueConstraint(
                fields=("key_hash",),
                name="api_key_key_hash_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(
                fields=["key_prefix"],
                name="api_key_prefix_index",
            ),
        ),
    ]
