# Generated by Django 6.0.2 on 2026-03-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_api_auth_hardening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apisolution',
            options={'verbose_name': 'API Solution', 'verbose_name_plural': 'API Solutions'},
        ),
    ]
