# Generated by Django 6.0.2 on 2026-03-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_apisolution_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APISolution',
            new_name='APIScopes',
        ),
        migrations.AlterModelOptions(
            name='apiscopes',
            options={'verbose_name': 'API Scope', 'verbose_name_plural': 'API Scopes'},
        ),
        migrations.RemoveConstraint(
            model_name='apiscopes',
            name='api_solution_slug_unique',
        ),
        migrations.AddConstraint(
            model_name='apiscopes',
            constraint=models.UniqueConstraint(fields=('slug',), name='api_scope_slug_unique'),
        ),
    ]
