# Generated by Django 6.0.2 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0005_rename_apisolution_apiscopes_alter_apiscopes_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apiscopes",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
