apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: postgres-managed-17
  namespace: uhn-services
spec:
  externalName: cc-uhn-services-postgres-17
  parameters:
    engine_version: '17'
    multi_az: false
    storage: 5
    public_access: true
    allow_access: "16.54.44.1/32, 3.97.157.105/32, 35.183.189.10/32"
  serviceOfferingName: postgresql-db
  servicePlanName: standard

---

apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: postgres-managed-17-binding
  namespace: uhn-services
spec:
  serviceInstanceName: postgres-managed-17
  secretName: postgres-managed-17-credentials
