apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: uhn-services
spec:
  selector:
    app: redis
  clusterIP: None
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: uhn-services
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
          - containerPort: 6379
